### ISSUE TITLE
Handle more than one connection request

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/pce#158]
At present `TEManager` is instantiated like so:

```python
    temanager = TEManager(topology_data, connection_request)
```

We do not have a way of adding different subsequent connection requests.  TEManager should be able to deal with concurrent connection requests and release requests, not just one.

Related to #122.  PR #156 adds some tests for VLAN assignments, but they exercise VLAN assignments by repeatedly issuing the same connection request.

**Comment by YufengXin** [comment]
yes. it was assumed sequential requests, maybe from the queue mechanism in sdx-controller. We should craft some tests here for sequential requests/releases.
Concurrent requests may be complex, because the network state needs to be synchronized in some way, for example, the vlans have to be locked to avoid concurrent assignment.
