### ISSUE TITLE
Removing deprecated files

### ISSUE THREAD

**Issue by YufengXin** [atlanticwave-sdx/pce#57]
te functions

needs to finish the unittest in SDX-Controller with the new implementation

**Comment by YufengXin** [comment]
[pce/src/LoadBalancing/RandomTopologyGenerator.py] -> [pce/src/Utility/randomTopologyGenerator.py] and [pce/src/Utility/randomConnectionGenerator.py]
[pce/src/LoadBalancing/MC_Solver.py] and [pce/src/LoadBalancing/LB_Utilization_Solver.py]. -> [pce/src/LoadBalancing/TE_Solver.py]
[pce/src/Heuristic/Heur.py]: this one particular function will be removed.

(And all the intermediate JSON files that were accidentally committed)

**Comment by sajith** [comment]
Taking stock of the changes and as a note to myself, these files will be entirely removed:

- [src/sdx/pce/LoadBalancing/RandomTopologyGenerator.py](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/LoadBalancing/RandomTopologyGenerator.py)
- [src/sdx/pce/LoadBalancing/MC_Solver.py](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/LoadBalancing/MC_Solver.py)
- [src/sdx/pce/LoadBalancing/LB_Utilization_Solver.py](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/LoadBalancing/LB_Utilization_Solver.py)
- [src/sdx/pce/Heuristic/Heur.py](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/Heuristic/Heur.py)

What in sdx-controller will break when old code is removed from pce?  Here's pce usage in sdx-controller:

- https://github.com/atlanticwave-sdx/sdx-controller/blob/ac42126dbd31b0bf7dcad998dec0bf7a0e8b5ff4/swagger_server/controllers/connection_controller.py#L8-L13
- https://github.com/atlanticwave-sdx/sdx-controller/blob/ac42126dbd31b0bf7dcad998dec0bf7a0e8b5ff4/tests/test_Solver.py#L9-L14


Two functions are actually used by sdx-controller: 

1. [sdx.pce.LoadBalancing.RandomTopologyGenerator.lbnxgraphgenerator()](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/LoadBalancing/RandomTopologyGenerator.py#L178) - has the signature `lbnxgraphgenerator(nodes, p, connection, g)`, of which `p` seems to be unused and `g` is a networkx graph.
2. [sdx.pce.LoadBalancing.runMC_Solver()](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/LoadBalancing/MC_Solver.py#L152) - expects input in `./tests/data/LB_data.json`, returns an `ordered_path_list` (which really is dict of `query` (connection request?) and `path`).

The above is in the order of usage: `lbnxgraphgenerator`'s output is `runMC_Solver()`'s input.  The new functions that should replace them are:

- [sdx.pce.Utility.randomConnectionGenerator.RandomConnectionGenerator.randomConnectionGenerator()]( https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/Utility/randomConnectionGenerator.py)
- [sdx.pce.Utility.randomTopologyGenerator.RandomTopologyGenerator.generate_graph()](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/Utility/randomTopologyGenerator.py#L68)
- [sdx.pce.LoadBalancing.TE_Solver.solve()](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/LoadBalancing/TE_Solver.py#L20)

In order to rewire things, we just have to remove the old code, use the new functions, and address the fallout: update tests in pce and update sdx-controller, in that order.  Should be simple, I hope. :-)

The function [dot_file()](https://github.com/atlanticwave-sdx/pce/blob/2c45525f4e0accc7142a2a1947c81d842fab0840/src/sdx/pce/Utility/randomTopologyGenerator.py#L156) also is a candidate for removal, possibly, but that is a separate issue (#72).
